projects:
  graphql-bootcamp:
    schemaPath: 'src/generated/schema.graphql'
    extensions:
      prisma: prisma/prisma.yml
      endpoints:
        default:
          url: 'http://localhost:4466/'
          subscription: 'ws://localhost:4466/'
        app:
          url: 'http://localhost:4000/'
          subscription: 'ws://localhost:4000/'
